# name: Website Template Build and push to deploy repository Worflow

# on:
#   workflow_dispatch:
#     if: contains('["TuuZzee"]', github.actor)
#   push:
#     branches: [ main, develop, stg-web-template, 'releases/web-template/**', 'test-stg/web-template/**' ]
#     paths:
#       - '.github/workflows/clPageBuildPushWebTemplate.yml'
#       - 'packages/websites/web-template/**'
#       - 'packages/shared/**'
#       - 'packages/storybook/**'
#       - '!packages/**/*.md'

# jobs:
#   build:
#     uses: TuuZzee/actions-monorepo/.github/workflows/fe-build-push.yaml@main # ./fe-build-push.yaml - create parent monorepo and move that action whitin to be able to call from here
#     secrets:
#       CLOUDBOT_GITHUB_TOKEN: ${{ secrets.CLOUDBOT_GITHUB_TOKEN }}
#     with:
#       project: 'web-template'
#       source-env-path: 'packages/websites/web-template/build'
#       dest-env-path: 'packages/websites/web-template'
