name: Build and push storybook service

on:
  workflow_dispatch:
    if: contains('["TuuZzee"]', github.actor)
  push:
    branches: [ develop ]
    paths:
      - '.github/workflows/clPageBuildPushStorybook.yml'
      - 'packages/storybook/**'
      - 'packages/shared/**'
      - '!packages/**/*.md'

jobs:
  build:
    uses: TuuZzee/fe-monorepo/.github/workflows/fe-build-push.yml@main
    secrets:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_NAME: ${{ secrets.USER_NAME }}
    with:
      project: 'storybook'
      source-env-path: 'packages/storybook/build'
      dest-env-path: 'packages/storybook'
