# name: CF Worker for groups deployment

# on:
#   workflow_dispatch:
#     if: contains('["TuuZzee"]', github.actor)
#   push:
#     branches: [ main ]
#     paths:
#     - '.github/workflows/clWorkerDeployAdminGoogleGroups.yml'
#     - 'packages/workers/fe-cl-admin-google-groups/**'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     name: Deploy
#     steps:
#       - uses: actions/checkout@v3
#       - name: Publish
#         uses: cloudflare/wrangler-action@1.3.0
#         with:
#           apiToken: ${{ secrets.CF_API_TOKEN }}
#           environment: 'production'
#           workingDirectory: 'packages/workers/fe-cl-admin-google-groups'
